=head1 BrowserStack Clone

This is another of my on going project to re-create the browserstack functionality to test software with selenium on multiple vms, browser versions and save the test logs.

=head2 Description

This browserstack clone is built on perl, with plack and mojolicious. When finished it will allow 

=head2 Screenshot

Here is a screenshot of one user test sessions. The user is able to see the virtual machine screen in real time. User can also see the selenium test session as it is being executed.

L<Screenshot|https://rawgit.com/hernan604/BrowserStack-Clone/master/app.png>

=begin HTML

<p><img src="https://rawgit.com/hernan604/BrowserStack-Clone/master/app.png" alt="Screenshot" /></p>

=end HTML

=head2 How-to prepare a windows box with selenium and some browsers

You will need to prepare as many windows boxes as you wish. On these vm you must install selenium-driver-server with a couple browsers. Then you must execute and start the selenium server.

=head3 Install firefox

Install some firefox and download the firefox webdriver from the selenium download page

=head3 Install chrome

Install some chrome and download the chrome webdriver from selenium download page

=head3 Install ie

Download the internet explorer webdriver from selenium downlolad page

=head3 Install 'Oracle' java 7

Got to oracle site and download java 7 and install on the windows box.

=head3 Install Selenium server

Download the selenium jar from seleniumhq.com > downloads

=head3 Start Selenium

Open cmd prompt and execute:

 java -jar ...

=head2 How-to Prepare a linux box with selenium and some browser

Here is described steps to prepare a linux box to become a selenium server

=head3 install linux google-chrome

 $ sudo add-apt-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
 $ wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
 $ sudo apt-get update
 $ sudo aptitude install google-chrome-stable

=head3 Install 'Oracle' java 7 on ubuntu linux

 sudo apt-get install python-software-properties
 sudo add-apt-repository ppa:webupd8team/java
 sudo apt-get update
 sudo apt-get install oracle-java7-installer

=head3 Install Selenium

Download the selenium jar from seleniumhq.com > downloads

=head3 Start Selenium

 java -jar ...

=head2 TODO 

Create new virtual machine in pristine mode (fresh virtualmachines)

Figure out how to create virtualmachines with selenium and iOS and Android

Other things...

Test opera drivers: 

=item Opera 12-15 https://github.com/operasoftware/operaprestodriver

=item Opera 15+ https://github.com/operasoftware/operachromiumdriver
